# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xz_DmFTxpv0py1CVxCXm5b5Ihfs3ujEs
"""

from fastapi import FastAPI
import joblib
import numpy as np

# 加载模型
model = joblib.load("electricity_model.pkl")

# 创建APP
app = FastAPI()

# 预测接口
@app.post("/predict")
def predict(
    household_size: int,
    num_applicants: int,
    outdoor_temp: float,
    hour_of_day: int,
    historical_consumption: float
):
    x = np.array([[
        household_size,
        num_applicants,
        outdoor_temp,
        hour_of_day,
        historical_consumption
    ]])
    pred = model.predict(x)[0]
    return {"predicted_electricity_consumption": round(float(pred), 2)}

# 主页
@app.get("/")
def home():
    return {"status": "API is running"}

"""# New section"""