# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xz_DmFTxpv0py1CVxCXm5b5Ihfs3ujEs
"""

from fastapi import FastAPI
import joblib
import numpy as np
import os

app = FastAPI()
model = None

@app.on_event("startup")
def load_model():
    global model
    print("当前目录：", os.getcwd())
    print("目录文件：", os.listdir())
    model = joblib.load("electricity_model.pkl")
    print("模型加载成功")

@app.post("/predict")
def predict(
    household_size: int,
    num_applicants: int,
    outdoor_temp: float,
    hour_of_day: int,
    historical_consumption: float
):
    x = np.array([[
        household_size,
        num_applicants,
        outdoor_temp,
        hour_of_day,
        historical_consumption
    ]])
    pred = model.predict(x)[0]
    return {"predicted_electricity_consumption": round(float(pred), 2)}

@app.get("/")
def home():
    return {"status": "API is running"}

"""# New section"""