# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xz_DmFTxpv0py1CVxCXm5b5Ihfs3ujEs
"""

# ======================
# 1. 安装需要的工具
# ======================
!pip install fastapi uvicorn pyngrok joblib scikit-learn

# ======================
# 2. 加载你训练好的模型
# ======================
import joblib
model = joblib.load("electricity_model.pkl")

# ======================
# 3. 创建 API 服务
# ======================
from fastapi import FastAPI
import numpy as np
from pyngrok import ngrok

app = FastAPI()

@app.post("/predict")
def predict(
    household_size: int,
    num_applicants: int,
    outdoor_temp: float,
    hour_of_day: int,
    historical_consumption: float
):
    x = np.array([[
        household_size,
        num_applicants,
        outdoor_temp,
        hour_of_day,
        historical_consumption
    ]])
    pred = model.predict(x)[0]
    return {"predicted_electricity_consumption": round(pred, 2)}

# ======================
# 4. 生成公开链接（别人可以用！）
# ======================
public_url = ngrok.connect(8000)
print("✅ 你的公开 API 地址：", public_url)
print("✅ 预测接口：", public_url + "/predict")

# ======================
# 5. 启动服务
# ======================
import uvicorn
uvicorn.run(app, host="0.0.0.0", port=8000)

"""# New section"""